name: 'Has Signed Canonical CLA'
description: 'This GitHub Action verifies whether or not a particular GitHub user has signed the Canonical Contributor Licence Agreement.'
inputs:
  username:
    description: 'The name of the GitHub user to verify.'
    required: true
  token:
    description: 'The access token of an existing member of the CanonicalContributorAgreement org with "read:org" permissions enabled.'
    required: true
  base_ref:
    description: 'The access token of an existing member of the CanonicalContributorAgreement org with "read:org" permissions enabled.'
    required: true
outputs:
  is_member:
    description: '"true" if the user has signed the agreement, otherwise "false".'
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'user-check'
  color: 'purple'
