name: 'Has Signed Canonical CLA'
description: 'This GitHub Action verifies whether or not the authors of a pull request have signed the Canonical CLA.'
inputs:
  accept-existing-contributors:
    description: 'Pass CLA check for existing project contributors'
    required: false
    default: false
  github-token:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to create a CLA comment on the pull request (default: {{ github.token }}).'
    default: '${{ github.token }}'
    required: false
  exempted-bots:
    description: 'GitHub usernames for exempted bot accounts.'
    default: 'dependabot,renovate'
    required: false
runs:
  using: 'node16'
  main: 'index.js'
branding:
  icon: 'user-check'
  color: 'purple'
