name: 'Has Signed Canonical CLA'
description: 'This GitHub Action verifies whether or not the authors of a pull request have signed the Canonical CLA.'
inputs:
  github-token:
    description: 'The GitHub access token.'
    required: false
    default: ${{ github.token }}
runs:
  using: 'node20'
  main: 'index.js'
branding:
  icon: 'user-check'
  color: 'purple'
