name: 'Has Signed Canonical CLA'
description: 'This GitHub Action verifies whether or not the authors of a pull request have signed the Canonical CLA.'
inputs:
  accept-existing-contributors:
    description: 'Pass CLA check for existing project contributors'
    required: false
    default: false
  GITHUB_TOKEN:
    description: 'The GitHub access token (e.g. secrets.GITHUB_TOKEN) used to create or update the comment and check for existing project contributors. This defaults to {{ github.token }}.'
    default: '${{ github.token }}'
    required: false
runs:
  using: 'node12'
  main: 'index.js'
branding:
  icon: 'user-check'
  color: 'purple'
