name: cla-check
on: [pull_request]

jobs:
  cla-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Check if CLA signed
        id: has_signed_cla
        uses: ./
        with:
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
          base_ref: ${{ github.base_ref }}
      - name: Verify result
        if: steps.has_signed_cla.outputs.has_signed == 'false'
        run: exit 1
