on: [pull_request]

jobs:
  has_signed_cla:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Has Signed Canonical CLA
        uses: ./
        id: has_signed_cla
        with:
          username: ${{ github.event.pull_request.user.login }}
          token: ${{ secrets.GITHUB_TOKEN }}
          base_ref: ${{ github.base_ref }}
      - name: Passed Check
        if: steps.has_signed_cla.outputs.has_signed == 'true'
        run: echo ${{ github.actor }} has signed the Canonical CLA
      - name: Failed Check
        if: steps.has_signed_cla.outputs.has_signed == 'false'
        run: echo ${{ github.actor }} has NOT signed the Canonical CLA
